### ISSUE TITLE
Loading screen detection broken in 1.10.2020.12.10

### ISSUE THREAD

**Issue by suushiemaniac** [loriswit/asl#1]
Superliminal version: 1.10.2020.12.10 (**Steam**)
LiveSplit version: 1.8.15
OS: Windows 10

I was delighted to see the auto splitter being updated for the most recent game version. I tried it during a run but the LiveSplit timer kept running during Loading Screens. I have added a screenshot to this issue to show the discrepancy between the in-game timer and LiveSplit.
![Screenshot 2021-01-24 155135](https://user-images.githubusercontent.com/6136469/105962649-631f2d00-6080-11eb-86e4-a6850414eb55.png)

I am using the "Default Splits" file from speedrun.com under "Resources": https://www.speedrun.com/superliminal/resources.
As I understand (and as it apparently works for all of the runs I've seen uploaded on YouTube) the timer is supposed to stop automatically during loading screens. Is this an actual bug or am I doing something wrong with the configuration of LiveSplit?

Thanks for your support and for maintaining this repository!

**Comment by loriswit** [comment]
The LiveSplit timer si supposed to display the time given by the in-game timer (the script reads its value directly from memory). If the LiveSplit timer differs from the in-game timer, it means that:

- either LiveSplit is comparing against real time, instead of game time (right-click LiveSplit → compare against → game time)
- or the pointer to the in-game timer is not reliable and we need to find a better one.

**Comment by suushiemaniac** [comment]
Thank you for the explanation. It turns out that I misconfigured LiveSplit and it was indeed set to compare against real time.
My apologies, I was so overwhelmed by the complexity of this program that I didn't even know that option existed. Problem solved :D
